---
kind: pipeline
type: docker
name: default

steps:
- name: npm update tag from git, build
  image: node:16
  commands:
  - git fetch --tags
  - bash set_version.sh
  - npm install
  - npm run build
  - npm run dev
  - npm install typedoc
  - npx typedoc src/plot-data.ts --out doc/build/typescript/

- name: test typescript code
  image: cypress/base
  commands:
    - npm install cypress --save-dev
    - cypress run

- name: python install, build doc run scripts
  image: python:3.8
  commands:
  - pip install sphinx sphinx_rtd_theme
  - python setup.py install
  - cd doc
  - make html

- name: upload npm
  image: plugins/npm
  when:
      event: tag
  settings:
    username: dessia
    token:
      from_secret: npm_token
    email: root@dessia.tech

- name: upload to cdn sid
  image: appleboy/drone-scp
  when:
      branch: master
      event: push
  settings:
    host: magenta.dessia.tech
    username: drone
    password:
      from_secret: ssh_drone_password
    target: /var/www/cdn/js/plot-data/sid/
    source: libdev/*
    strip_components: 1
    overwrite: true

- name: upload to cdn version
  image: appleboy/drone-scp
  when:
      event: tag
  settings:
    host: magenta.dessia.tech
    username: drone
    password:
      from_secret: ssh_drone_password
    target: /var/www/cdn/js/plot-data/${DRONE_TAG}/
    source: libdev/*
    strip_components: 1
    overwrite: true

- name: upload to cdn latest
  image: appleboy/drone-scp
  when:
      event: tag
  settings:
    host: magenta.dessia.tech
    username: drone
    password:
      from_secret: ssh_drone_password
    target: /var/www/cdn/js/plot-data/latest/
    source: libdev/*
    strip_components: 1
    overwrite: true


- name: upload_doc_typescript
  image: appleboy/drone-scp
  when:
    branch: master
    event: push
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/plot_data/typescript
    source: doc/build/typescript/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password
    overwrite: true

- name: check code complexity, docs & code quality
  image: python:3.9
  commands:
  - pip install radon pydocstyle pylint
  - ./code_quality.sh
  - python code_pylint.py

- name: check pep8 formatting
  image: python:3.9
  commands:
    - git fetch --tags
    - pip3 install -U pip autopep8
    - bash code_pep8.sh

- name: sdist
  image: python:3.8
  commands:
  - python setup.py sdist

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: upload_doc_python
  image: appleboy/drone-scp
  when:
    branch: master
    event: push
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/plot_data/python
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password

