---
kind: pipeline
type: docker
name: default

steps:
- name: merge master on dev
  image: alpine/git
  when:
    event: push
    branch: master
  commands:
  - git fetch origin dev
  - git checkout dev
  - git merge master
  - git push

- name: notify upstream merge failure
  when:
    event: push
    branch: master
    status:
    - failure
  image: drillster/drone-email
  failure: ignore
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech

- name: npm update tag from git, build
  image: node:16
  commands:
  - git fetch --tags
  - bash set_version.sh
  - npm install
  - npm run build
  - npm run dev
  - npm install typedoc
  - npx typedoc

- name: install, run scripts and build doc
  image: python:3.9
  commands:
  - git fetch --tags
  - pip install .[doc,test]
  - cd ./script
  - coverage run --source plot_data ci_tests.py --path="/drone/src/cypress/data_src"
  - coverage report
  - coverage html
  - cd ../doc
  - make html

  volumes:
  - name: jsons
    path: /drone/src/cypress/data_src

- name: Test typescript with cypress
  image: cypress/included:12.6.0
  commands:
    - ./node_modules/.bin/cypress install --force
    - npm install
    - npm run test
  volumes:
  - name: jsons
    path: /drone/src/cypress/data_src

- name: upload cypress reports to cdn
  image: appleboy/drone-scp
  when:
    event: push
    status:
    - success
    - failure
  ignore: failure
  settings:
    host: magenta.dessia.tech
    username: drone
    password:
      from_secret: ssh_drone_password
    target: /var/www/cdn/tests/plot_data/${DRONE_BRANCH}
    source: cypress/results/*
    strip_components: 2
    overwrite: true

- name: upload npm
  image: plugins/npm
  when:
      event: tag
  settings:
    username: dessia
    token:
      from_secret: npm_token
    email: root@dessia.tech

- name: check changelog update
  image: python:3.9
  when:
    event: pull_request
    branch:
      - master
      - dev
  commands:
    - bash code_changelog.sh

- name: upload to cdn sid
  image: appleboy/drone-scp
  when:
      branch: master
      event: push
  settings:
    host: magenta.dessia.tech
    username: drone
    password:
      from_secret: ssh_drone_password
    target: /var/www/cdn/js/plot-data/sid/
    source: libdev/*
    strip_components: 1
    overwrite: true

- name: upload to cdn version
  image: appleboy/drone-scp
  when:
      event: tag
  settings:
    host: magenta.dessia.tech
    username: drone
    password:
      from_secret: ssh_drone_password
    target: /var/www/cdn/js/plot-data/${DRONE_TAG}/
    source: libdev/*
    strip_components: 1
    overwrite: true

- name: upload to cdn latest
  image: appleboy/drone-scp
  when:
      event: tag
  settings:
    host: magenta.dessia.tech
    username: drone
    password:
      from_secret: ssh_drone_password
    target: /var/www/cdn/js/plot-data/latest/
    source: libdev/*
    strip_components: 1
    overwrite: true


- name: upload_doc_typescript
  image: appleboy/drone-scp
  when:
    branch: master
    event: push
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/plot_data/typescript
    source: doc/build/typescript/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password
    overwrite: true

- name: check code complexity, docs & code quality pre-commit
  image: python:3.9
  commands:
  - pip install pylint==2.16.2 pre-commit
  - python code_pylint.py
  - pre-commit run -a

- name: check pep8 formatting
  image: python:3.9
  commands:
    - git fetch --tags
    - pip3 install -U pip autopep8
    - bash code_pep8.sh

- name: sdist
  image: python:3.9
  commands:
  - python setup.py sdist

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: upload_doc_python
  image: appleboy/drone-scp
  when:
    branch: master
    event: push
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/plot_data/python
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password

volumes:
- name: jsons
  temp: {}
