---
kind: pipeline
type: docker
name: default

steps:
- name: npm update tag from git, build
  image: node:14
  commands:
  - git fetch --tags
  - npm config set git-tag-version=false 
  - version=`git describe --tags`
  - npm version $${version}
  - npm install
  - npm run-script build
  - npm install typedoc
  - npx typedoc src/plot-data.ts --out doc/build/typescript/

- name: upload npm
  image: plugins/npm
  when:
      event: tag
  settings:
    username: dessia
    password:
      from_secret: npm_password
    email: root@dessia.tech

- name: upload to cdn sid
  image: appleboy/drone-scp
  when:
      branch: master
      event: push
  settings:
    host: magenta.dessia.tech
    username: drone
    password:
      from_secret: ssh_drone_password
    target: /var/www/cdn/js/plot-data/sid/
    source: lib/*
    strip_components: 1
    rm: true

- name: upload to cdn version
  image: appleboy/drone-scp
  when:
      event: tag
  settings:
    host: magenta.dessia.tech
    username: drone
    password:
      from_secret: ssh_drone_password
    target: /var/www/cdn/js/plot-data/${DRONE_TAG}/
    source: lib/*
    strip_components: 1

- name: upload to cdn latest
  image: appleboy/drone-scp
  when:
      event: tag
  settings:
    host: magenta.dessia.tech
    username: drone
    password:
      from_secret: ssh_drone_password
    target: /var/www/cdn/js/plot-data/latest/
    source: lib/*
    strip_components: 1
    rm: true


- name: upload_doc_typescript
  image: appleboy/drone-scp
  when:
    branch: master
    event: push
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/plot_data/typescript
    source: doc/build/typescript/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password



- name: install, build doc run scripts
  image: python:3.8
  commands:
  - pip install sphinx sphinx_rtd_theme
  - python setup.py install
  - cd doc
  - make html


- name: develop
  image: python:3.8
  commands:
  - python setup.py develop

- name: sdist
  image: python:3.8
  commands:
  - python setup.py sdist

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: upload_doc_python
  image: appleboy/drone-scp
  when:
    branch: master
    event: push
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/plot_data/python
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password

- name: notify by email
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
